version: '3.3'

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      DATABASE_NAME: ${MSSQL_DB}
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    ports:
      - ${MSSQL_PORT}:${MSSQL_PORT}
    volumes:
      - mssql-volume:${MSSQL_VOLUME}
    networks:
      - mssql-networks


volumes:
  mssql-volume:

networks:
  mssql-networks:
    driver: bridge