version: '3.3'

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      DATABASE_NAME: ${MSSQL_DB}
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    ports:
      - ${MSSQL_PORT}:${MSSQL_PORT}
    volumes:
      - mssql-volume:${MSSQL_VOLUME}
    networks:
      - mssql-networks

  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - ${VAULT_PORT}:${VAULT_PORT}
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_ADDR: ${VAULT_DEV_LISTEN_ADDRESS}
    restart: always
    
    
volumes:
  mssql-volume:

networks:
  mssql-networks:
    driver: bridge